# Generated by Django 4.2.3 on 2023-07-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_closed_listings_winner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='unique_watchlist'),
        ),
    ]
