# Generated by Django 4.2.3 on 2023-07-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist_unique_watchlist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='watchlist',
            name='unique_watchlist',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'listing')},
        ),
    ]
