# Generated by Django 4.2.3 on 2023-07-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
