# Generated by Django 4.2.3 on 2023-07-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='winner',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
